@echo off
echo Instalando proyecto Laravel...
cd c:\Users\fvazq\Music\campus
composer create-project laravel/laravel laravel --prefer-dist --no-interaction
echo Copiando archivos personalizados...
xcopy /E /Y laravel-temp\* laravel\
echo Configurando .env...
copy laravel\.env.example laravel\.env
echo Generando clave...
cd laravel
php artisan key:generate
echo Configurando base de datos SQLite...
New-Item database\database.sqlite -ItemType File -Force
echo Ejecutando migraciones...
php artisan migrate --force
echo Iniciando servidor...
php artisan serve --host=127.0.0.1 --port=8000
pause 